### PR TITLE
docs: fix typo in README

### PR DESCRIPTION
**Pull request by patoroco**
Just fixing a typo in the `README.md`

### CODE REVIEW

**Comment by karlderkaefer** [comment]
thank for providing this improvement can you change your commit message to apply to [semantic commit|https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716]? e.g. `docs: fix typo in readme`

**Comment by patoroco** [comment]
done!

**Comment by karlderkaefer** [comment]
please add @patoroco for doc.

**Comment by karlderkaefer** [comment]
@patoroco pls rename the commit message of gith history, the merge request is not that important 
```
git commit --amend
```

**Comment by karlderkaefer** [comment]
@all-contributors please add @patoroco for doc.

**Comment by patoroco** [comment]
commit message updated, sorry but I thought that you were using squash for PRs, so the message name would be the title of the PR :D

**Comment by patoroco** [comment]
@karlderkaefer you need to approve the PR to leave the auto merge works :D

**Review by karlderkaefer — APPROVED** [review]

**Pull request merged**
